### ISSUE TITLE
Live streaming demo not working due to mixed content

### ISSUE THREAD

**Issue by jankais3r** [marek-simonik/record3d-simple-wifi-streaming-demo#1]
First of all thank, you for adding the WiFi streaming option. Instant purchase.

Unfortunately, the [live demo](https://marek-simonik.github.io/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo/) does not work because GitHub Pages are served over HTTPS while the Record3d app streams the video over HTTP.

When run locally everything works as expected.

![image](https://user-images.githubusercontent.com/2159464/106332759-b1524d00-6287-11eb-97ab-00b54d6cd177.png)

**Comment by marek-simonik** [comment]
Thank you for purchasing and for reporting this issue! I was developing the demo on localhost where everything works perfectly, and it did not even occur to me to test Wi-Fi Streaming on Github Pages (I tested only the mp4 playback, which works and I wrongly assumed Wi-Fi streaming would work too).

Right now, I can think of two possible solution:
1. Running HTTPS server on iOS — but in that case, I would need to have a self-signed certificate, which the browser would not be happy to see either.
2. Turning off HTTPS for the Github Pages — I am not completely sure about be the security implications. The demo does not upload videos nor the streamed data anywhere though, so the only exposed resources would be jQuery and other publicly available libraries from CDNs.

I will think about more alternatives.

**Comment by jankais3r** [comment]
I am afraid that there is no obvious solution to this. Modern browsers made it close to impossible to resolve any sort of certificate irregularity without a deliberate intervention of end-user (flags or special launch parameters). And GitHub [no longer allows](https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https) HTTPS-less hosting of Pages. It's a shame to not have a way to demo this feature online, but since people have to buy the IAP anyway before they can try it out, I would assume that they will be able to host the site locally. Maybe you could embed a video showcasing the live streaming and have only the mp4 video playback as a live demo...

**Comment by marek-simonik** [comment]
In [this Github Pages documentation](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#about-custom-domain-configuration) (step 8), I found that if you use a custom domain for Github Pages, then the "Enforce HTTPS" option is optional:

> Optionally, to enforce HTTPS encryption for your site, select Enforce HTTPS…

I will probably try to host Github Pages on my own domain to see if "Enforce HTTPS" will become optional. I currently cannot think of any critical security issue that would arise when hosting the demo over HTTP.

**Comment by marek-simonik** [comment]
Unfortunately, disabling "Enforce HTTPS" did not help — I was still redirected to the HTTPS version.

However, I think I "solved" this problem; the demo is now hosted on a new — HTTP only — domain: [http://record3d.xyz/](http://record3d.xyz/).

Please try the new link and let me know if it works for you too (in Chrome or Safari; because it still does not work in Firefox), so that I can close this issue.

**Comment by jankais3r** [comment]
Works! 🚀

**Comment by marek-simonik** [comment]
Perfect, thanks for confirming and for reporting it!
